# uranus-telegram 配置文件模板,启动时加载 /etc/hackernel/telegram.yaml

# 从 Telegram @BotFather 获取的 token
token: ""
# chat ID
id: 0

# SQLite Data Source Name ,https://github.com/mattn/go-sqlite3#connection-string
dsn: "/var/lib/hackernel/telegram.db?cache=shared&mode=rwc&_journal_mode=WAL"

