# uranus-web 配置文件模板,启动时加载 /etc/hackernel/web.yaml

# SQLite Data Source Name ,https://github.com/mattn/go-sqlite3#connection-string
dsn: "/var/lib/hackernel/web.db?cache=shared&mode=rwc&_journal_mode=WAL"

# web 服务监听的地址
listen: "0.0.0.0:80"
